services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=honeypot_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - honeypot_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "honeypot_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=honeypot_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - honeypot_network

networks:
  honeypot_network:
    driver: bridge
